php_variations:
  - name: cli
    default: true
  - name: frankenphp
    excluded_minor_versions:
      - "7.4"
      - "8.0"
      - "8.1"
      - "8.2"

php_versions:
  - major: "7"
    minor_versions:
      - minor: "7.4"
        base_os:
          - name: alpine3.16
          - name: bullseye
        patch_versions:
          - 7.4.33
  - major: "8"
    minor_versions:
      - minor: "8.0"
        base_os:
          - name: alpine3.16
          - name: bullseye
        patch_versions:
          - 8.0.30
      - minor: "8.1"
        base_os:
          - name: alpine3.21
          - name: bookworm
          - name: trixie
        patch_versions:
          # - 8.1.28 # Pull latest from Official PHP source
      - minor: "8.2"
        base_os:
          - name: alpine3.21
          - name: alpine3.22
          - name: bookworm
          - name: trixie
        patch_versions:
        #   - 8.2.18 # Pull latest from Official PHP source
      - minor: "8.3"
        base_os:
          - name: alpine3.21
          - name: alpine3.22
          - name: bookworm
          - name: trixie
        patch_versions:
          # - 8.3.6 # Pull latest from Official PHP source
      - minor: "8.4"
        base_os:
          - name: alpine3.21
          - name: alpine3.22
          - name: bookworm
          - name: trixie
        patch_versions:
        #   - 8.4.1 # Pull latest from Official PHP source
      # PHP 8.5-rc has a blocking bug in a dependency that is not yet fixed.
      # 
      # - minor: "8.5-rc"
      #   base_os:
      #     - name: alpine3.21
      #     - name: alpine3.22
      #     - name: bookworm
      #     - name: trixie
      #   patch_versions:
      #     - 8.5-rc

operating_systems:
  - family: alpine
    versions:
      - name: "Alpine 3.16"
        version: alpine3.16
        number: 3.16
      - name: "Alpine 3.17"
        version: alpine3.17
        number: 3.17
      - name: "Alpine 3.18"
        version: alpine3.18
        number: 3.18
      - name: "Alpine 3.19"
        version: alpine3.19
        number: 3.19
      - name: "Alpine 3.20"
        version: alpine3.20
        number: 3.20
      - name: "Alpine 3.21"
        version: alpine3.21
        number: 3.21
      - name: "Alpine 3.22"
        version: alpine3.22
        number: 3.22
  - family: debian
    default: true
    versions:
      - name: "Debian Bullseye"
        version: bullseye
        number: 11
      - name: "Debian Bookworm"
        version: bookworm
        number: 12
      - name: "Debian Trixie"
        version: trixie
        number: 13