name: Docker Publish (Dev "Main" Images)

on:
  workflow_dispatch:

jobs:
  build-dev-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      registry-repositories: "ghcr.io/yieldstudio/php-dev" # Set to our development repository
      tag-prefix: ''
      release-type: latest
    secrets: inherit

  build-sail-images:
    needs: build-dev-images
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      base-repository: "ghcr.io/yieldstudio/php-dev" # Use the dev base images
      registry-repositories: "ghcr.io/yieldstudio/sail-dev" # Set to our development repository
      tag-prefix: ''
      php-versions-config: 'scripts/conf/sail-versions-base-config.yml'
      php-versions-file: 'scripts/conf/sail-versions.yml'
      release-type: latest
      artifact-name: 'sail-versions.yml'
    secrets: inherit