name: Docker Publish (Dev "Main" Images)

on:
  workflow_dispatch:

jobs:
  build-dev-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      registry-repositories: "ghcr.io/yieldstudio/php-dev" # Set to our development repository
      tag-prefix: ''
      release-type: latest
    secrets: inherit