name: Docker Publish (PR Images)

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to build (leave empty for manual branch build)'
        required: false
        type: string
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/**
      - .github/workflows/action_publish-images-**
      - .github/workflows/service_docker-**
      - scripts/**

jobs:
  build-dev-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      registry-repositories: "ghcr.io/yieldstudio/php-dev"
      # Use PR number from input if provided, otherwise use the PR event number
      tag-prefix: ${{ inputs.pr_number || github.event.pull_request.number }}
      release-type: testing
      push-to-registry: >-
        ${{ 
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.type == 'Organization')
        }}
    secrets: inherit

  build-sail-images:
    needs: build-dev-images
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      base-repository: "ghcr.io/yieldstudio/php-dev"
      registry-repositories: "ghcr.io/yieldstudio/sail-dev"
      tag-prefix: ${{ inputs.pr_number || github.event.pull_request.number }}
      php-versions-config: 'scripts/conf/sail-versions-base-config.yml'
      php-versions-file: 'scripts/conf/sail-versions.yml'
      artifact-name: 'sail-versions.yml'
      release-type: testing
      prepend-tag-to-php-version: true
      push-to-registry: >-
        ${{ 
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.type == 'Organization')
        }}
    secrets: inherit
